# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "aesni_intel" "cryptd" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2b367078-a37e-444f-b218-78c66bb8bcf1";
      fsType = "btrfs";
      options = [ "compress=zstd:6" "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/c78fd7dc-3c4a-4f88-8a33-f1c2b46327ca";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2b367078-a37e-444f-b218-78c66bb8bcf1";
      fsType = "btrfs";
      options = [ "compress=zstd:6" "subvol=@home" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/2b367078-a37e-444f-b218-78c66bb8bcf1";
      fsType = "btrfs";
      options = [ "compress=zstd:6" "subvol=@var" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2b367078-a37e-444f-b218-78c66bb8bcf1";
      fsType = "btrfs";
      options = [ "compress=zstd:6" "subvol=@nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BE00-5508";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
