# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zpool/RPOOL/NixOS/Clean";
      fsType = "zfs";
    };

  fileSystems."/etc" =
    { device = "zpool/RPOOL/NixOS/Persist/etc";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zpool/RPOOL/NixOS/Persist/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "zpool/RPOOL/NixOS/Persist/var";
      fsType = "zfs";
    };

  fileSystems."/var/lib/flatpak" =
    { device = "zpool/DPOOL/Data/Flatpak";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zpool/DPOOL/Home/NixOS";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BE00-5508";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
