# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2f6b6499-2a27-4583-847f-dd70b9fcb036";
    fsType = "btrfs";
    options = [
      "subvol=SYSTEM/NixOS/@"
      "compress=zstd:6"
    ];
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/327f2e02-1e4f-48b2-87f0-797c481850c9";

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/2f6b6499-2a27-4583-847f-dd70b9fcb036";
    fsType = "btrfs";
    options = [
      "subvol=SYSTEM/NixOS/@var"
      "compress=zstd:6"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/2f6b6499-2a27-4583-847f-dd70b9fcb036";
    fsType = "btrfs";
    options = [
      "subvol=SYSTEM/NixOS/@nix"
      "compress=zstd:6"
    ];
  };

  fileSystems."/etc" = {
    device = "/dev/disk/by-uuid/2f6b6499-2a27-4583-847f-dd70b9fcb036";
    fsType = "btrfs";
    options = [
      "subvol=SYSTEM/NixOS/@etc"
      "compress=zstd:6"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/2f6b6499-2a27-4583-847f-dd70b9fcb036";
    fsType = "btrfs";
    options = [
      "subvol=DATA/Home/NixOS"
      "compress=zstd:6"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/2f6b6499-2a27-4583-847f-dd70b9fcb036";
    fsType = "btrfs";
    options = [
      "subvol=DATA/Share"
      "compress=zstd:6"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9699-52A2";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/7c5f1768-bf41-4349-9b92-4b53880a8e05"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
