# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "aesni_intel"
    "cryptd"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d8b51e69-ff95-4e60-8373-9581da1d6c7d";
    fsType = "btrfs";
    options = [
      "subvol=SYSTEM/NixOS/@"
      "compress=zstd:6"
    ];
  };

  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-uuid/eb063fae-136d-476c-9b90-83d1056b513d";
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/d8b51e69-ff95-4e60-8373-9581da1d6c7d";
    fsType = "btrfs";
    options = [
      "subvol=SYSTEM/NixOS/@var"
      "compress=zstd:6"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d8b51e69-ff95-4e60-8373-9581da1d6c7d";
    fsType = "btrfs";
    options = [
      "subvol=SYSTEM/NixOS/@nix"
      "compress=zstd:6"
    ];
  };

  fileSystems."/etc" = {
    device = "/dev/disk/by-uuid/d8b51e69-ff95-4e60-8373-9581da1d6c7d";
    fsType = "btrfs";
    options = [
      "subvol=SYSTEM/NixOS/@etc"
      "compress=zstd:6"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/d8b51e69-ff95-4e60-8373-9581da1d6c7d";
    fsType = "btrfs";
    options = [
      "subvol=DATA/@home"
      "compress=zstd:6"
    ];
  };

  fileSystems."/var/lib/sbctl" = {
    device = "/dev/disk/by-uuid/d8b51e69-ff95-4e60-8373-9581da1d6c7d";
    fsType = "btrfs";
    options = [
      "subvol=DATA/@sbctl"
      "compress=zstd:6"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/d8b51e69-ff95-4e60-8373-9581da1d6c7d";
    fsType = "btrfs";
    options = [
      "subvol=DATA/@swap"
      "compress=none"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0C54-13CC";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
